name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release-wasm:
        type: boolean
        default: false



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Test
        run: |
          build/tests



  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.69
          actions-cache-folder: 'emsdk-cache'

      - name: Deno
        run: |
          ./deno.sh task cache
      
      - name: Build
        run: |
          emcc -v
          mkdir build-wasm
          cd build-wasm
          emcmake cmake ..                      \
            -DCMAKE_BUILD_TYPE=Release          \
            -DCMAKE_VERBOSE_MAKEFILE=ON
          emmake make
          cd ..
          ./deno.sh bundle --minify --outdir=./bundle src/wasm-big-image.ts
          ls -halt

      - name: Test
        run: |
          ./run_tests_deno.sh
      
      - name: Archive JS module
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: |
            bundle/wasm-big-image.js
            src/wasm-big-image.d.ts
          if-no-files-found: error


  release-wasm:
    needs:   build-wasm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.inputs.release-wasm == 'true' }}

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: modules
          path: artifact/

      - name: Release
        run: |
          TAGNAME=v$(date +%F)
          echo $TAGNAME

          git fetch origin wasm-releases
          git checkout wasm-releases
          cp artifact/wasm-big-image.d.ts ./
          cp artifact/build-wasm/bundle/wasm-big-image.js ./
          rm -r artifact
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./wasm-big-image.*
          git commit -m "$TAGNAME"
          git tag --force $TAGNAME
          git push origin wasm-releases
          git push origin --tags




